Repository SaraMarhoum/WebDesign-Sass, pull requests merged in 2020-02, with the labels that each got.

#5 modify header
  css/style.css
  img/stock-photo-at-work.jpg
  index.html
  sass/style.scss
Labels: documentation

#7 modify 2 header
  css/style.css
  img/Web_Design_Promotional_Video.mp4
  img/header-play-butn.png
  index.html
  sass/style.scss
Labels: documentation

#10 mySection_Team
  css/style.css
  css/style.css.map
  img/MbrFour.png
  img/MbrOne.png
  img/MbrThree.png
  img/MbrTwo.png
  index.html
  sass/style.scss
Labels: invalid

#12 section_realisons
  css/style.css
  css/style.css.map
  img/user.png
  index.html
  sass/style.scss
Labels: question
